### ISSUE TITLE
system vs DNS resolution

### ISSUE THREAD

**Issue by zimbatm** [ycd/dstp#11]
One distinction that could be useful is to do both a resolution through the system, like by calling `gethostbyname()` in the glibc, and doing the DNS resolution manually by querying the root DNS servers or 8.8.8.8. Both can yield different results and help inform why a host might fail.

There are many reasons why a system resolver might yield a different result. A few that come to mind:
* caching: the system resolver, or ISP resolver might be caching some old results
* /etc/hosts file has an entry for that hostname
* the /etc/resolv.conf has a search domain, that has an entry. If the original hostname doesn't exist, it would fall back on that one.

**Comment by ycd** [comment]
Great idea! 

I was looking for a way to implement this that can work cross-platform. Then i came across [`net.LookupHost()`](https://pkg.go.dev/net#LookupHost) which looks great. 

> LookupHost looks up the given host using the local resolver. It returns a slice of that host's addresses.

**Comment by ycd** [comment]
This feature is accessible with v0.3.0 release JFYK.
