### ISSUE TITLE
I`m try to build bstp,but i got a error!

### ISSUE THREAD

**Issue by JohyC** [ycd/dstp#15]
I`m try to build bstp,but i got a error!
no Go files in /root/wapper/dstp;
I don't understand what happened.
![image](https://user-images.githubusercontent.com/38210128/141671467-743e79d9-acd4-4958-ba14-36cf000b9249.png)

**Comment by ycd** [comment]
Hey @JohyC, thanks for the report. 

I moved the main package to the `cmd/dstp/main.go` and forgot to update the README.

Using `go build cmd/dstp/main.go` or using `go install github.com/ycd/dstp/cmd/dstp`should resolve your issue.
