### ISSUE TITLE
ping: socket: permission denied on WSL

### ISSUE THREAD

**Issue by mevjak** [ycd/dstp#21]
I got following error in WSL (Windows Subsystem for Linux) terminal (Ubuntu 20.04):

```
me@JNNH00004L:~$ dstp https://google.com
Ping: failed to run ping: socket: permission denied
DNS: failed to run ping: socket: permission denied
SystemDNS: resolving 216.58.201.78, 2a00:1450:4014:800::200e
TLS: certificate is valid for 56 more days
HTTPS: got 200 OK
```

Ping command is working OK:

```
me@JNNH00004L:~$ ping google.com
PING google.com (216.58.201.78) 56(84) bytes of data.
64 bytes from prg03s01-in-f78.1e100.net (216.58.201.78): icmp_seq=1 ttl=113 time=24.6 ms
64 bytes from prg03s01-in-f78.1e100.net (216.58.201.78): icmp_seq=2 ttl=113 time=20.9 ms
```

**Comment by davidaparicio** [comment]
As the error message suggests, it looks a permission issue. Did you try with 'sudo' in front of the command ? Or with the root account to see if the socket is accessible ? :)

**Comment by ycd** [comment]
Hey @mevjak, in some hosts dstp currently requires sudo due this issue:  https://github.com/go-ping/ping/issues/180.

Until it is resolved there is no workaround for running it without sudo privileges AFAICT.

**Comment by zimbatm** [comment]
One potential workaround is to look for and shell out to the `ping` binary, who usually has the setuid bit enabled. If the program cannot find any solution, it would probably have to mark this check as not available (which is different from a failure).

**Comment by mevjak** [comment]
Sorry, I forgot to mention that the problem is the same with sudo or under root and/or terminal running as administrator:
```
me@JNNH00004L:~$ sudo dstp https://google.com
Ping: failed to run ping: socket: permission denied
DNS: failed to run ping: socket: permission denied
SystemDNS: resolving 216.58.201.78, 2a00:1450:4014:800::200e
TLS: certificate is valid for 56 more days
HTTPS: got 200 OK

root@JNNH00004L:/# dstp https://google.com
Ping: failed to run ping: socket: permission denied
DNS: failed to run ping: socket: permission denied
SystemDNS: resolving 216.58.201.78, 2a00:1450:4014:800::200e
TLS: certificate is valid for 56 more days
HTTPS: got 200 OK
```

**Comment by mevjak** [comment]
This workaround helped:

To allow the use of ICMP sockets by ping enable them for root:

1. sysctl -w net.ipv4.ping_group_range="0 0"

Make ping SGID to root:

2. chmod g+s /usr/bin/ping

**Comment by ycd** [comment]
Thanks for sharing that @mevjak. But AFAIK go-ping library doesn't executes the `ping` under the hood, just sends pure ICMP packets. 

Have you tried running again after the this step?
> sysctl -w net.ipv4.ping_group_range="0 0"

Nice idea @zimbatm, as a fallback option that seems plausible.

**Comment by mevjak** [comment]
I can confirm that. It not depends on `ping`. It is working just after setting:

> sysctl -w net.ipv4.ping_group_range="0 0"
