### ISSUE TITLE
[FEATURE] Add cron-job ability and announcers

### ISSUE THREAD

**Issue by ycd** [ycd/dstp#24]
Add cron-job ability so that the dstp can re-run the tests against the given site in the specified amount of time and add the logic for announcing results in slack, discord etc. 

An example usage in my mind:

```
$ export SLACK_TOKEN="token"
$ export SLACK_CHANNEL_ID="1234567"

$ dstp --cron=300 --announce="slack" 8.8.8.8
```

Then this re-runs the tests in every 5 minutes(300 sec) and announces the results to given slack channel. 

* [ ] Add cron-job logic
* [ ] Add announcer for Slack. 
* [ ] Add announcer for Discord.

**Comment by mauri** [comment]
Hello! any reason to not just use `watch` for this? as in `watch -n 300 dstp 8.8.8.8`

Is the goal to support full crontab syntax in the cron parameter? i.e. `dstp --cron='*/5 * * * *' 8.8.8.8`

**Comment by ycd** [comment]
Hello @mauri, supporting the crontab syntax is a great idea!

Using watch is also great for running locally but if you are running `dstp` inside some server, k8s  providing an out-of-box announcer and cron-job mechanism seems like a right way to go.

**Comment by davidaparicio** [comment]
Completed with a Pull Request / new release ? :)

**Comment by ycd** [comment]
I thought about it and decided keep it simple and not to add a feature that is outside of the scope.

I think It's still very easy to achieve this feature either in Kubernetes or Bare Metal like @mauri mentioned.
