### ISSUE TITLE
[Documentation] Update README for installation with go command

### ISSUE THREAD

**Issue by Lyokolux** [ycd/dstp#30]
Hello there :wave: 

I am currently trying the tool and I installed it with `go install`.

By copy/pasting the command from the CLI, I got the following error

```
go install: version is required when current directory is not in a module
	Try 'go install github.com/ycd/dstp/cmd/dstp@latest' to install the latest version
```

Using the following does not solve the installation: 
```bash
go install github.com/ycd/dstp/cmd/dstp@latest
```

Do you have an idea how it could be installed with go ?

**Comment by ycd** [comment]
Hi @Lyokolux, 

Which version of go are you using?

**Comment by Lyokolux** [comment]
> Hi @Lyokolux,
> 
> Which version of go are you using?

go version go1.16.4 linux/amd64

**Comment by ycd** [comment]
I am going to update the `README` but it is quite interesting that it doesn't works even with `@latest` tag.
