### ISSUE TITLE
go install

### ISSUE THREAD

**Issue by nikolaydubina** [ycd/dstp#5]
Is it possible to install this tool with `go install`? Any reasons why you guys prefer go build + cp? Interesting tool!

**Comment by ycd** [comment]
Hey, i thought about adding that to documentation but `go install github.com/ycd/dstp/cmd@latest` didn't done the job for me.

Let me know if it works for you, then i can add it to README.

**Comment by boratanrikulu** [comment]
It works but `go install` sets binary name as `cmd` instead of `dstp`. I guess there is no option like `-o <name>` for `go install`.

![dstp](https://user-images.githubusercontent.com/20258973/141064947-59cd70a1-715b-4190-a5c2-56b4f93d31be.png)

**Comment by nikolaydubina** [comment]
Right, I saw this issue too. ~If so then either package name has to be changed~ (this is not possible as package has to be `main` 🤦🏻‍♂️) or leaf path of package import path in module. ~I can try different name later too. I am interested if this works!~

**Comment by nikolaydubina** [comment]
Maybe moving this main pkg CLI into `cmd/dstp` would work for you guys? Or root directory (given CLI is main function of project)

**Comment by ycd** [comment]
Oh i wasn't aware of the fact that it installs the executable as `cmd` @boratanrikulu, nice catch! 

Yeah, moving the main package to `cmd/dstp` should work then, i will update the actions etc and move it to cmd/dstp @nikolaydubina 👍 .

**Comment by ycd** [comment]
With #10,  now you can install `dstp` with `go install`:rocket: 

```zsh
go install github.com/ycd/dstp/cmd/dstp
```

Thanks for reporting and researching about this issue @boratanrikulu, @nikolaydubina 👍
